-- 시퀀스 삭제
-- drop sequence member_seq;
DROP SEQUENCE "SEQ_ALA_NO";
DROP SEQUENCE "SEQ_ANS_NO";
DROP SEQUENCE "SEQ_FAQ_NO";
DROP SEQUENCE "SEQ_MNO";
DROP SEQUENCE "SEQ_NOT_NO";
DROP SEQUENCE "SEQ_PROJ_NO";
DROP SEQUENCE "SEQ_PROJ_RV_NO";
DROP SEQUENCE "SEQ_REP_NO";
DROP SEQUENCE "SEQ_RES_NO";
DROP SEQUENCE "SEQ_RPL_NO";
DROP SEQUENCE "SEQ_RWD_NO";
DROP SEQUENCE "SEQ_SUBRL_NO";
DROP SEQUENCE "SEQ_USER_NO";
-- 시퀀스 생성
-- CREATE SEQUENCE "SEQ_ALA_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 79 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE "SEQ_ALA_NO";
CREATE SEQUENCE "SEQ_ANS_NO";
CREATE SEQUENCE "SEQ_FAQ_NO";
CREATE SEQUENCE "SEQ_MNO";
CREATE SEQUENCE "SEQ_NOT_NO";
CREATE SEQUENCE "SEQ_PROJ_NO";
CREATE SEQUENCE "SEQ_PROJ_RV_NO";
CREATE SEQUENCE "SEQ_REP_NO";
CREATE SEQUENCE "SEQ_RES_NO";
CREATE SEQUENCE "SEQ_RPL_NO";
CREATE SEQUENCE "SEQ_RWD_NO";
CREATE SEQUENCE "SEQ_SUBRL_NO";
CREATE SEQUENCE "SEQ_USER_NO";
   
-- 테이블 삭제
DROP TABLE "USER_TB" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT_TB" CASCADE CONSTRAINTS;
DROP TABLE "REWARD" CASCADE CONSTRAINTS;
DROP TABLE "COMMUNITY" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "FOLLOW_TB" CASCADE CONSTRAINTS;
DROP TABLE "LIKE_TB" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "REWARD_OPTION" CASCADE CONSTRAINTS;
DROP TABLE "COMMUNITY_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "RESERVE_REWARD" CASCADE CONSTRAINTS;
DROP TABLE "RESERVE" CASCADE CONSTRAINTS;
DROP TABLE "VISIT_PER_DAY" CASCADE CONSTRAINTS;
DROP TABLE "VISIT_TOTAL" CASCADE CONSTRAINTS;
DROP TABLE "BLAME_TB" CASCADE CONSTRAINTS;
DROP TABLE "BLAME_COMMUNITY" CASCADE CONSTRAINTS;
DROP TABLE "AUTO_LOGIN" CASCADE CONSTRAINTS;
DROP TABLE "RESERVE_STATUS_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "ROLE" CASCADE CONSTRAINTS;
DROP TABLE "USER_ROLE" CASCADE CONSTRAINTS;
DROP TABLE "FILE" CASCADE CONSTRAINTS;
DROP TABLE "FILE_PROJECT" CASCADE CONSTRAINTS;
DROP TABLE "FILE_USER" CASCADE CONSTRAINTS;
DROP TABLE "COUPON" CASCADE CONSTRAINTS;
DROP TABLE "USER_COUPON" CASCADE CONSTRAINTS;
DROP TABLE "OAUTH_ID" CASCADE CONSTRAINTS;
DROP TABLE "CONFIRM_EMAIL" CASCADE CONSTRAINTS;


-- 테이블 생성

CREATE TABLE "OAUTH_ID" (
	"OAUTH_ID_NO"	NUMBER		NOT NULL,
	"OAUTH_ID_USER_ID"	NUMBER		NOT NULL,
	"OAUTH_ID_ACCESS_TOKEN"	VARCHAR2(255)		NOT NULL,
	"OAUTH_ID_PROVIDER"	VARCHAR2(255)		NOT NULL
);
ALTER TABLE "OAUTH_ID" ADD CONSTRAINT "PK_OAUTH_ID" PRIMARY KEY ( "OAUTH_ID_NO" );

CREATE TABLE "CONFIRM_EMAIL" (
	"USER_NO"	NUMBER		NOT NULL,
	"DATE_EXPIRED"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SECURED_KEY"	VARCHAR2(255)	NOT NULL
);
ALTER TABLE "CONFIRM_EMAIL" ADD CONSTRAINT "PK_CONFIRM_EMAIL" PRIMARY KEY ( "USER_NO" );

CREATE TABLE "FILE"(
	"FILE_NO" NUMBER PRIMARY KEY,
	"UPLOAD_NAME" VARCHAR2(256) NOT NULL,
	"SAVE_NAME" VARCHAR2(256) NOT NULL UNIQUE, 
	"FILE_SIZE" NUMBER DEFAULT 0, 
	"FILE_TYPE" VARCHAR2(256)
);
-- CREATE SEQUENCE TIP_TMP_FILE_SEQ;

CREATE TABLE "FILE_PROJECT"(
	"FILE_NO" NUMBER NOT NULL,
	"BOARD_NO" NUMBER NOT NULL
);

CREATE TABLE "FILE_USER"(
	"FILE_NO" NUMBER NOT NULL,
	"USER_NO" NUMBER NOT NULL
);


CREATE TABLE "COUPON" (
	"COUPON_NO"	NUMBER		NOT NULL,
	"RATE"	NUMBER		NOT NULL,
	"CATEGORY_ID"	NUMBER		NOT NULL,
	"CREATEDAT"	NUMBER		NOT NULL,
	"MODIFIEDAT"	NUMBER		NOT NULL,
	"EXPIREDAT"	NUMBER		NOT NULL
);

CREATE TABLE "USER_COUPON" (
	"USER_COUPON_NO"	NUMBER		NOT NULL,
	"USER_COUPON_USER_NO"	NUMBER		NOT NULL,
	"USER_COUPON_COUPON_NO"	NUMBER		NOT NULL,
	"USED"	NUMBER		NOT NULL
);

CREATE TABLE "ROLE" (
	"ROLE_NO"	NUMBER		NOT NULL,
	"ROLE_AUTHORITY"	VARCHAR2(255)		NOT NULL
);
ALTER TABLE "ROLE" ADD CONSTRAINT "PK_ROLE" PRIMARY KEY ( "ROLE_NO" );
COMMENT ON TABLE "ROLE" IS '관리자 권한';
COMMENT ON COLUMN "ROLE"."ROLE_AUTHORITY" IS '모든/프로젝트/계정/공지사항';

CREATE TABLE "USER_ROLE" (
	"USER_ROLE_NO"	NUMBER		NOT NULL,
	"USER_ROLE_USER_NO"	NUMBER		NOT NULL,
	"USER_ROLE_ROLE_NO"	NUMBER		NOT NULL,
);
ALTER TABLE "USER_ROLE" ADD CONSTRAINT "PK_USER_ROLE" PRIMARY KEY ( "USER_ROLE_NO" );
COMMENT ON TABLE "USER_ROLE" IS '유저-권한 관계';

CREATE TABLE "AUTO_LOGIN" (
	"AUTO_LOGIN_USER_NO"	NUMBER		NOT NULL,
	"AUTO_LOGIN_SESSIONKEY"	VARCHAR2(500)		NULL,
	"AUTO_LOGIN_EXPIRYDATE"	DATE		NULL
);
ALTER TABLE "AUTO_LOGIN" ADD CONSTRAINT "PK_AUTO_LOGIN" PRIMARY KEY ( "AUTO_LOGIN_USER_NO" );
COMMENT ON COLUMN "AUTO_LOGIN"."AUTO_LOGIN_USER_NO" IS '자동로그인할 유저 번호';
COMMENT ON COLUMN "AUTO_LOGIN"."AUTO_LOGIN_SESSIONKEY" IS '세션키 저장하는 컬럼';
COMMENT ON COLUMN "AUTO_LOGIN"."AUTO_LOGIN_EXPIRYDATE" IS '세션키 만료되는 날짜';

CREATE TABLE "RESERVE_STATUS_CATEGORY" (
	"RESERVE_ST_NO"	NUMBER		NOT NULL,
	"RESERVE_ST_DETAIL"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "RESERVE_STATUS_CATEGORY" ADD CONSTRAINT "PK_RESERVE_STATUS_CATEGORY" PRIMARY KEY ( "RESERVE_ST_NO" );
COMMENT ON COLUMN "AUTO_LOGIN"."AUTO_LOGIN_USER_NO" IS '주문 예약/결제 완료/예약 취소';

CREATE TABLE "USER_TB" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(100)		NOT NULL,
	"USER_PWD"	VARCHAR2(100)		NOT NULL,
	"USER_EMAIL_AUTH"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"USER_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"USER_LOGIN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_DATE_CREATED"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_DATE_UPDATED"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_ADDR"	VARCHAR2(1000)		NULL,
	"USER_PHONE"	VARCHAR2(100)		NULL,
	"USER_PROFILE_IMG"	VARCHAR2(1000)		NULL,
	"USER_PROFILE_TXT"	VARCHAR2(1000)		NULL
);
ALTER TABLE "USER_TB" ADD CONSTRAINT "PK_USER_TB" PRIMARY KEY ( "USER_NO" );
COMMENT ON COLUMN "USER_TB"."USER_NO" IS 'SEQ_USER_NO';
COMMENT ON COLUMN "USER_TB"."USER_EMAIL_AUTH" IS '이메일인증시 Y /EMAIL_AUTH';
COMMENT ON COLUMN "USER_TB"."USER_STATUS" IS '탈퇴시 N';
COMMENT ON COLUMN "USER_TB"."USER_DATE_CREATED" IS 'ENROLL_DATE/가입일자';
COMMENT ON COLUMN "USER_TB"."USER_DATE_UPDATED" IS 'MODIFY_DATE/수정일자';
COMMENT ON COLUMN "USER_TB"."USER_ADDR" IS 'ADDRESS/주소';
COMMENT ON COLUMN "USER_TB"."USER_PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "USER_TB"."USER_PROFILE_IMG" IS '프로필 글';



CREATE TABLE "PROJECT_TB" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"PROJECT_TITLE"	VARCHAR2(100)		NOT NULL,
	"PROJECT_STITLE"	VARCHAR2(200)		NOT NULL,
	"PROJECT_GOAL"	NUMBER		NOT NULL,
	"PROJECT_THUMB_IMG"	VARCHAR2(400)		NOT NULL,
	"PROJECT_START_DT"	DATE		NOT NULL,
	"PROJECT_CLOSE_DT"	DATE		NOT NULL,
	"PROJECT_HASHTAG"	VARCHAR2(4000)		NULL,
	"PROJECT_MAIN_IMG"	VARCHAR2(400)		NOT NULL,
	"PROJECT_SUMMARY"	VARCHAR2(400)		NOT NULL,
	"PROJECT_STORY"	CLOB		NOT NULL,
	"PROJECT_AT_NM"	VARCHAR2(100)		NOT NULL,
	"PROJECT_AT_PF"	VARCHAR2(400)		NOT NULL,
	"PROJECT_AT_SNS1"	VARCHAR2(100)		NULL,
	"PROJECT_AT_SNS2"	VARCHAR2(100)		NULL,
	"PROJECT_AT_CONT"	VARCHAR2(100)		NULL,
	"PROJECT_AT_EM"	VARCHAR2(100)		NULL,
	"PROJECT_ER_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROJECT_MF_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROJECT_WRITER"	NUMBER		NOT NULL,
	"PROJECT_CT_NO"	NUMBER		NOT NULL,
	"PROJECT_ST_NO"	NUMBER		NOT NULL
);
ALTER TABLE "PROJECT_TB" ADD CONSTRAINT "PK_PROJECT_TB" PRIMARY KEY ( "PROJECT_NO" );
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_NO" IS 'SEQ_PROJ_NO';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_START_DT" IS 'START_DATE/시작일';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_CLOSE_DT" IS 'CLOSE_DATE/종료일';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_NM" IS 'ARTIST_NAME/아티스트이름';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_PF" IS 'ARTIST_PROFILE/아티스트프로필사진';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_SNS1" IS 'ARTIST_SNS';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_SNS2" IS 'ARTIST_SNS';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_CONT" IS 'ARTIST_CONTRACT/아티스트연락처';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_AT_EM" IS 'ARTIST_EMAIL';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_ER_DT" IS 'ENROLL_DATE/프로젝트등록일자';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_MF_DT" IS 'MODIFY_DATE/프로젝트수정일자';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_CT_NO" IS 'CATEGORY_NO/프로젝트카테고리번호';
COMMENT ON COLUMN "PROJECT_TB"."PROJECT_ST_NO" IS 'STATUS_NO/프로젝트상태번호';

CREATE TABLE "REWARD" (
	"REWARD_NO"	NUMBER		NOT NULL,
	"REWARD_PRICE"	NUMBER		NOT NULL,
	"REWARD_NAME"	VARCHAR2(200)		NOT NULL,
	"REWARD_EXPLAIN"	VARCHAR2(4000)		NOT NULL,
	"REWARD_LIMIT"	NUMBER	DEFAULT 0	NOT NULL,
	"REWARD_SHIP_CDT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"REWARD_SHIP_DT"	DATE		NOT NULL,
	"REWORD_OP_ADD"	VARCHAR2(4000)		NULL,
	"REWORD_REF_PNO"	NUMBER		NOT NULL,
	"REWORD_OP_NO"	NUMBER		NOT NULL
);
ALTER TABLE "REWARD" ADD CONSTRAINT "PK_REWARD" PRIMARY KEY ( "REWARD_NO" );
COMMENT ON COLUMN "REWARD"."REWARD_NO" IS 'SEQ_RWD_NO';
COMMENT ON COLUMN "REWARD"."REWARD_EXPLAIN" IS '리워드 설명';
COMMENT ON COLUMN "REWARD"."REWARD_LIMIT" IS '리워드 제한수량';
COMMENT ON COLUMN "REWARD"."REWARD_SHIP_CDT" IS 'SHIP_CONDITION/배송조건';
COMMENT ON COLUMN "REWARD"."REWARD_SHIP_DT" IS 'SHIP_DATE/배송예정일';

CREATE TABLE "COMMUNITY" (
	"COMMUNITY_NO"	NUMBER		NOT NULL,
	"COMMUNITY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMUNITY_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"COMMUNITY_WRI_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMUNITY_MODI_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMUNITY_REF_PNO"	NUMBER		NOT NULL,
	"COMMUNITY_WRITER"	NUMBER		NOT NULL,
	"COMMUNITY_CATEGORY_NO"	NUMBER		NOT NULL,
	"COMMUNITY_PARENT_NO"	NUMBER		NOT NULL
);
ALTER TABLE "COMMUNITY" ADD CONSTRAINT "PK_COMMUNITY" PRIMARY KEY ( "COMMUNITY_NO" );
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_NO" IS 'SEQ_RPL_NO';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_STATUS" IS 'Y/N';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_WRI_DT" IS 'COMMUNITY_WRITE_DATE/ 댓글작성일';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_MODI_DT" IS 'COMMUNITY_MODIFY_DATE/댓글수정일';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(300)		NOT NULL,
	"NOTICE_CONTENT"	CLOB		NOT NULL,
	"NOTICE_ER_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_MF_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"NOTICE_WRITER"	NUMBER		NOT NULL
);
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ( "NOTICE_NO" );
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS 'SEQ_NOT_NO';
COMMENT ON COLUMN "NOTICE"."NOTICE_ER_DT" IS 'ENROLL_DATE/작성일';
COMMENT ON COLUMN "NOTICE"."NOTICE_MF_DT" IS 'MODIFY_DATE/수정일';

CREATE TABLE "FOLLOW_TB" (
	"FOLLOW"	NUMBER		NOT NULL,
	"FOLLOWER"	NUMBER		NOT NULL
);
ALTER TABLE "FOLLOW_TB" ADD CONSTRAINT "PK_FOLLOW_TB" PRIMARY KEY ( "FOLLOW", "FOLLOWER" );

CREATE TABLE "LIKE_TB" (
	"LIKE_USER"	NUMBER		NOT NULL,
	"LIKE_PRJ"	NUMBER		NOT NULL
);
ALTER TABLE "LIKE_TB" ADD CONSTRAINT "PK_LIKE_TB" PRIMARY KEY ( "LIKE_USER", "LIKE_PRJ" );

CREATE TABLE "PROJECT_CATEGORY" (
	"PROJECT_CT_NO"	NUMBER		NOT NULL,
	"PROJECT_CT_NAME"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "PROJECT_CATEGORY" ADD CONSTRAINT "PK_PROJECT_CATEGORY" PRIMARY KEY ( "PROJECT_CT_NO" );
COMMENT ON COLUMN "PROJECT_CATEGORY"."PROJECT_CT_NO" IS 'CATEGORY_NO/프로젝트카테고리번호';
COMMENT ON COLUMN "PROJECT_CATEGORY"."PROJECT_CT_NAME" IS 'CATEGORY_NAME/프로젝트카테고리이름';

CREATE TABLE "REWARD_OPTION" (
	"REWORD_OP_NO"	NUMBER		NOT NULL,
	"REWORD_OP_DETAIL"	VARCHAR2(1000)		NOT NULL
);
ALTER TABLE "REWARD_OPTION" ADD CONSTRAINT "PK_REWARD_OPTION" PRIMARY KEY ( "REWORD_OP_NO" );
COMMENT ON COLUMN "REWARD_OPTION"."REWORD_OP_NO" IS 'OPTION_NO/리워드 옵션 번호';
COMMENT ON COLUMN "REWARD_OPTION"."REWORD_OP_DETAIL" IS 'OPTION_DETAIL/리워드옵션상세';

CREATE TABLE "COMMUNITY_CATEGORY" (
	"COMMUNITY_CATEGORY_NO"	NUMBER		NOT NULL,
	"PEPLY_CG_NM"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "COMMUNITY_CATEGORY" ADD CONSTRAINT "PK_COMMUNITY_CATEGORY" PRIMARY KEY ( "COMMUNITY_CATEGORY_NO" );
COMMENT ON COLUMN "COMMUNITY_CATEGORY"."COMMUNITY_CATEGORY_NO" IS 'CATEGORY_NO/댓글카테고리번호';
COMMENT ON COLUMN "COMMUNITY_CATEGORY"."PEPLY_CG_NM" IS 'CATEGORY_NAME/댓글카테고리이름';


CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(300)		NOT NULL,
	"FAQ_CONTENT"	CLOB		NOT NULL,
	"FAQ_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FAQ_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FAQ_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"FAQ_WRITER"	NUMBER		NOT NULL
);
ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY ( "FAQ_NO" );
COMMENT ON COLUMN "FAQ"."FAQ_NO" IS 'SEQ_FAQ_NO';

CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"REVIEW_TITLE"	VARCHAR2(300)		NOT NULL,
	"REVIEW_CONTENT"	CLOB		NOT NULL,
	"REVIEW_ER_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_MF_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"REVIEW_REF_PNO"	NUMBER		NOT NULL,
	"REVIEW_WRITER"	NUMBER		NOT NULL
);
ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ( "REVIEW_NO" );
COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS 'SEQ_PROJ_RV_NO';

CREATE TABLE "PROJECT_STATUS" (
	"PROJECT_ST_NO"	NUMBER		NOT NULL,
	"PROJECT_ST_DETAIL"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "PROJECT_STATUS" ADD CONSTRAINT "PK_PROJECT_STATUS" PRIMARY KEY ( "PROJECT_ST_NO" );
COMMENT ON COLUMN "PROJECT_STATUS"."PROJECT_ST_NO" IS 'STATUS_NO/프로젝트상태번호';
COMMENT ON COLUMN "PROJECT_STATUS"."PROJECT_ST_DETAIL" IS 'STATUS_DETAIL/프로젝트상태상세내용';

CREATE TABLE "RESERVE_REWARD" (
	"RESERVE_NO"	NUMBER		NOT NULL,
	"REWARD_NO"	NUMBER		NOT NULL,
	"REWARD_SUM"	NUMBER	DEFAULT 1	NOT NULL
);
ALTER TABLE "RESERVE_REWARD" ADD CONSTRAINT "PK_RESERVE_REWARD" PRIMARY KEY ( "RESERVE_NO", "REWARD_NO" );
COMMENT ON COLUMN "RESERVE_REWARD"."REWARD_SUM" IS '리워드개수';

CREATE TABLE "RESERVE" (
	"RESERVE_NO"	NUMBER		NOT NULL,
	"BILLINGKEY"	VARCHAR2(4000)		NOT NULL,
	"ADDITIONAL"	NUMBER	DEFAULT 0	NOT NULL,
	"RESERVE_DATE"	DATE		NOT NULL,
	"RESERVE_NAME"	VARCHAR2(100)		NOT NULL,
	"RESERVE_CONTRACT"	NUMBER		NOT NULL,
	"RESERVE_ADDRESS"	VARCHAR2(4000)		NOT NULL,
	"RESERVE_REQUEST"	VARCHAR2(300)		NULL,
	"RESERVE_USER"	NUMBER		NOT NULL
);
ALTER TABLE "RESERVE" ADD CONSTRAINT "PK_RESERVE" PRIMARY KEY ( "RESERVE_NO" );
COMMENT ON COLUMN "RESERVE"."RESERVE_NO" IS 'SEQ_RES_NO';
COMMENT ON COLUMN "RESERVE"."RESERVE_NAME" IS '배송이름';
COMMENT ON COLUMN "RESERVE"."RESERVE_CONTRACT" IS '배송전화번호';
COMMENT ON COLUMN "RESERVE"."RESERVE_ADDRESS" IS '배송주소';
COMMENT ON COLUMN "RESERVE"."RESERVE_REQUEST" IS '배송시요청사항';

CREATE TABLE "VISIT_PER_DAY" (
	"VISIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);
ALTER TABLE "VISIT_PER_DAY" ADD CONSTRAINT "PK_VISIT_PER_DAY" PRIMARY KEY ( "VISIT_DATE", "USER_NO" );

CREATE TABLE "VISIT_TOTAL" (
	"VISIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TOTAL_COUNT"	NUMBER		NOT NULL
);
ALTER TABLE "VISIT_TOTAL" ADD CONSTRAINT "PK_VISIT_TOTAL" PRIMARY KEY ( "VISIT_DATE" );
-- blame

CREATE TABLE "BLAME_TB" (
	"BLAME_NO"	NUMBER		NOT NULL,
	"BLAME_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLAME_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BLAME_REF_PNO"	NUMBER		NOT NULL,
	"BLAME_WRITER"	NUMBER		NOT NULL
);
ALTER TABLE "BLAME_TB" ADD CONSTRAINT "PK_BLAME_TB" PRIMARY KEY ( "BLAME_NO" );
COMMENT ON COLUMN "BLAME_TB"."BLAME_NO" IS 'SEQ_REP_NO';

CREATE TABLE "BLAME_COMMUNITY" (
	"BLAME_RP_NO"	NUMBER		NOT NULL,
	"BLAME_RP_CONTENT"	VARCHAR2(4000)		NULL,
	"BLAME_RP_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLAME_RP_REF_RNO"	NUMBER		NOT NULL,
	"BLAME_RP_WRITER"	NUMBER		NOT NULL
);
ALTER TABLE "BLAME_COMMUNITY" ADD CONSTRAINT "PK_BLAME_COMMUNITY" PRIMARY KEY ( "BLAME_RP_NO" );
COMMENT ON COLUMN "BLAME_COMMUNITY"."BLAME_RP_NO" IS 'SEQ_ANS_NO';
-- Table Constraint
-- PK
-- FK
ALTER TABLE "PROJECT_TB" ADD CONSTRAINT "FK_USER_TB_TO_PROJECT_TB_1" FOREIGN KEY ( "PROJECT_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "PROJECT_TB" ADD CONSTRAINT "FK_PROJECT_CATEGORY_TO_PROJECT_TB_1" FOREIGN KEY ( "PROJECT_CT_NO" ) REFERENCES "PROJECT_CATEGORY" ( "PROJECT_CT_NO" );
ALTER TABLE "PROJECT_TB" ADD CONSTRAINT "FK_PROJECT_STATUS_TO_PROJECT_TB_1" FOREIGN KEY ( "PROJECT_ST_NO" ) REFERENCES "PROJECT_STATUS" ( "PROJECT_ST_NO" );
ALTER TABLE "REWARD" ADD CONSTRAINT "FK_PROJECT_TB_TO_REWARD_1" FOREIGN KEY ( "REWORD_REF_PNO" ) REFERENCES "PROJECT_TB" ( "PROJECT_NO" );
ALTER TABLE "REWARD" ADD CONSTRAINT "FK_REWARD_OPTION_TO_REWARD_1" FOREIGN KEY ( "REWORD_OP_NO" ) REFERENCES "REWARD_OPTION" ( "REWORD_OP_NO" );
ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_PROJECT_TB_TO_COMMUNITY_1" FOREIGN KEY ( "COMMUNITY_REF_PNO" ) REFERENCES "PROJECT_TB" ( "PROJECT_NO" );
ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_USER_TB_TO_COMMUNITY_1" FOREIGN KEY ( "COMMUNITY_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_COMMUNITY_CATEGORY_TO_COMMUNITY_1" FOREIGN KEY ( "COMMUNITY_CATEGORY_NO" ) REFERENCES "COMMUNITY_CATEGORY" ( "COMMUNITY_CATEGORY_NO" );
ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_USER_TB_TO_NOTICE_1" FOREIGN KEY ( "NOTICE_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "FOLLOW_TB" ADD CONSTRAINT "FK_USER_TB_TO_FOLLOW_TB_1" FOREIGN KEY ( "FOLLOW" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "FOLLOW_TB" ADD CONSTRAINT "FK_USER_TB_TO_FOLLOW_TB_2" FOREIGN KEY ( "FOLLOWER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "LIKE_TB" ADD CONSTRAINT "FK_USER_TB_TO_LIKE_TB_1" FOREIGN KEY ( "LIKE_USER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "LIKE_TB" ADD CONSTRAINT "FK_PROJECT_TB_TO_LIKE_TB_1" FOREIGN KEY ( "LIKE_PRJ" ) REFERENCES "PROJECT_TB" ( "PROJECT_NO" );
ALTER TABLE "FAQ" ADD CONSTRAINT "FK_USER_TB_TO_FAQ_1" FOREIGN KEY ( "FAQ_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_PROJECT_TB_TO_REVIEW_1" FOREIGN KEY ( "REVIEW_REF_PNO" ) REFERENCES "PROJECT_TB" ( "PROJECT_NO" );
ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_USER_TB_TO_REVIEW_1" FOREIGN KEY ( "REVIEW_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "RESERVE_REWARD" ADD CONSTRAINT "FK_RESERVE_TO_RESERVE_REWARD_1" FOREIGN KEY ( "RESERVE_NO" ) REFERENCES "RESERVE" ( "RESERVE_NO" );
ALTER TABLE "RESERVE_REWARD" ADD CONSTRAINT "FK_REWARD_TO_RESERVE_REWARD_1" FOREIGN KEY ( "REWARD_NO" ) REFERENCES "REWARD" ( "REWARD_NO" );
ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_USER_TB_TO_RESERVE_1" FOREIGN KEY ( "RESERVE_USER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "VISIT_PER_DAY" ADD CONSTRAINT "FK_USER_TB_TO_VISIT_PER_DAY_1" FOREIGN KEY ( "USER_NO" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "BLAME_TB" ADD CONSTRAINT "FK_PROJECT_TB_TO_BLAME_TB_1" FOREIGN KEY ( "BLAME_REF_PNO" ) REFERENCES "PROJECT_TB" ( "PROJECT_NO" );
ALTER TABLE "BLAME_TB" ADD CONSTRAINT "FK_USER_TB_TO_BLAME_TB_1" FOREIGN KEY ( "BLAME_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "BLAME_COMMUNITY" ADD CONSTRAINT "FK_BLAME_TB_TO_BLAME_COMMUNITY_1" FOREIGN KEY ( "BLAME_RP_REF_RNO" ) REFERENCES "BLAME_TB" ( "BLAME_NO" );
ALTER TABLE "BLAME_COMMUNITY" ADD CONSTRAINT "FK_USER_TB_TO_BLAME_COMMUNITY_1" FOREIGN KEY ( "BLAME_RP_WRITER" ) REFERENCES "USER_TB" ( "USER_NO" );
ALTER TABLE "AUTO_LOGIN" ADD CONSTRAINT "FK_USER_TB_TO_AUTO_LOGIN_1" FOREIGN KEY ( "AUTO_LOGIN_USER_NO" ) REFERENCES "USER_TB" ( "USER_NO" );
